# Generated by Django 5.1.7 on 2025-04-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_charity_email_alter_charity_image_alter_domain_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charities.domain'),
        ),
    ]
