# Generated by Django 5.1.7 on 2025-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_donation_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card')], max_length=10, null=True),
        ),
    ]
