# Generated by Django 5.1.7 on 2025-04-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_donation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
